---
- name: Get all managed nodepool descriptions
  command: >
    gcloud compute instances list
      --format="value(networkInterfaces[0].accessConfigs[0].natIP)"
      --filter="metadata.items.key:k2nodepool AND metadata.items.value:{{ item.name }}"
      --project {{ kraken_config.providerConfig.project }}
  register: node_ips_out
  with_items: "{{ kraken_config.nodepool }}"

- name: Generate ssh inventory
  template: src=ssh_config.jinja2
    dest="{{ config_base | expanduser }}/{{ kraken_config.cluster }}/ssh_config"