---
- name: Create terraform folder
  file:
    path: "{{ config_base }}/{{ cluster.name }}"
    state: directory

- name: Create module folders
  file:
    path: "{{ config_base }}/{{ cluster.name }}/{{ item }}"
    state: directory
  with_items:
    - vpc
    - route53
    - keypair
    - subnet
    - cluster_secgroup
    - etcd
    - master
    - node
    - bastion

- name: Generate kraken.provider.aws.tf file
  template: src=kraken.provider.aws.tf.jinja2
            dest="{{ config_base }}/{{ cluster.name }}/kraken.provider.aws.tf"

- name: Generate module files
  template: src={{ item.source }}
            dest="{{ config_base }}/{{ cluster.name }}/{{ item.dest }}/module.tf"
  with_items:
    - { source: kraken.provider.aws.module.vpc.tf.jinja2, dest: vpc }
    - { source: kraken.provider.aws.module.route53.tf.jinja2, dest: route53 }
    - { source: kraken.provider.aws.module.keypair.tf.jinja2, dest: keypair }
    - { source: kraken.provider.aws.module.subnet.tf.jinja2, dest: subnet }
    - { source: kraken.provider.aws.module.cluster_secgroup.tf.jinja2, dest: cluster_secgroup }
    - { source: kraken.provider.aws.module.etcd.tf.jinja2, dest: etcd }
    - { source: kraken.provider.aws.module.master.tf.jinja2, dest: master }
    - { source: kraken.provider.aws.module.node.tf.jinja2, dest: node }
    - { source: kraken.provider.aws.module.bastion.tf.jinja2, dest: bastion }
