---
# Module dependencies are recurive as of terraform 0.10.x.
# See: https://github.com/hashicorp/terraform/pull/9236
- set_fact:
    tf_modules:
      - vpc
      - route53
      - keypair
      - subnet
      - cluster_secgroup
      - bastion
      - etcd
      - master
      - node

- set_fact:
    tf_etcd_modules: "{{ tf_modules | difference(['master', 'node']) }}"
    tf_k8s_modules: "{{ tf_modules | difference(['etcd']) }}"

- set_fact:
    tf_etcd_targets: "{% for module in tf_etcd_modules %} -target module.{{ module }}{{ ' ' if not loop.last else '' }}{% endfor %}"
    tf_k8s_targets: "{% for module in tf_k8s_modules %} -target module.{{ module }}{{ ' ' if not loop.last else '' }}{% endfor %}"

- name:
  set_fact:
    cluster: "{{ a_cluster }}"
    etcd_status_lock_filename: "{{ config_base }}/{{ cluster.name }}/etcd.status.lock"
    ssl_cert_common_name: "*.{{ cluster.providerConfig.region }}.elb.amazonaws.com"

- name: Ensure cluster directories exist
  file:
    path: "{{ config_base }}/{{ cluster.name }}/"
    state: directory
    recurse: yes

- include: aws-certs.yaml
  when: kraken_action == 'up'

# Terraform resources which have prevent_destroy set to true will not be
# destroyed, even when `terraform destroy` is called. To avoid the potential
# for infrastructure data loss, some resources are only allowed to be deleted
# when all of the infrastructure is being destroyed by the down action.
- include: aws-template.yaml
  vars:
    prevent_destroy: "{{ 'false' if kraken_action == 'down' else 'true' }}"

- stat:
    path: etcd_status_lock_filename
  register: etcd_status_lock_file

- name: Create etcd nodes
  include: terraform-apply-etcd.yaml
  when:
    - not etcd_status_lock_file.stat.exists
    - kraken_action == 'up'

- name: Create partial ssh_config in order to check etcd health
  include_role:
    name: kraken.ssh/kraken.ssh.aws

- name: Wait for etcd nodes to form clusters
  include: wait-for-etcd.yaml
  with_items:
    - "{{ cluster.nodePools }}"
  loop_control:
    loop_var: nodePool
  when:
    - nodePool.etcdConfigs is defined
    - not etcd_status_lock_file.stat.exists
    - kraken_action == 'up'
    - not (dryrun | bool)
    - not distro == 'ubuntu'

- name: Ensure etcd_status_lock file exists
  copy:
    content: ""
    dest: "{{ config_base }}/{{ cluster.name }}/etcd.status.lock"

- include: aws-action-dryrun.yaml

- name: Create/destroy k8s nodes
  include: aws-action.yaml
  when: not (dryrun | bool)
