---
- name: Set aws credential lookup parameters
  set_fact:
    aws_credentials_access_lookup_string: >
        aws_access_key_id
        section={{ kraken_config.providerConfig.authentication.credentialsProfile }}
        file={{ kraken_config.providerConfig.authentication.credentialsFile }}
    aws_credentials_secret_lookup_string: >
        aws_secret_access_key
        section={{ kraken_config.providerConfig.authentication.credentialsProfile }}
        file={{ kraken_config.providerConfig.authentication.credentialsFile }}

- name: Set aws keys from credentials file if it exists
  set_fact:
    aws_access_key: "{{ lookup('ini', aws_credentials_access_lookup_string) }}"
    aws_secret_key: "{{ lookup('ini', aws_credentials_secret_lookup_string) }}"
  when: >
      kraken_config.providerConfig.authentication.credentialsFile not in ['',None]
      and kraken_config.providerConfig.authentication.credentialsProfile not in ['',None]
      and kraken_config.providerConfig.authentication.credentialsFile|is_file

- name: Override aws keys if set explicitly
  set_fact:
      aws_access_key: "{{ kraken_config.providerConfig.authentication.accessKey }}"
      aws_secret_key: "{{ kraken_config.providerConfig.authentication.accessSecret }}"
  when: >
      kraken_config.providerConfig.authentication.accessKey not in ['',None]
      and kraken_config.providerConfig.authentication.accessSecret not in ['',None]

- name: Validate aws_access_key
  fail:
    msg: "AWS access key not configured"
  when: aws_access_key|default('') == ''

- name: Validate aws_secret_key
  fail:
    msg: "AWS secret key not configured"
  when: aws_secret_key|default('') == ''


- include: aws-certs.yaml
  when: kraken_action == 'up'
- include: aws-template.yaml
- include: aws-action.yaml
