---
- name: Get terraform modules
  command: >
    terraform get -no-color -update=true {{ config_base | expanduser }}/{{ cluster.name }}
  args:
    chdir: "{{ config_base | expanduser }}/{{ cluster.name }}"

- name: Apply terraform configuration to current state of etcd
  command: >
    terraform apply -target module.etcd -input=false -no-color {{ config_base | expanduser }}/{{ cluster.name }}
  args:
    chdir: "{{ config_base | expanduser }}/{{ cluster.name }}"
  register: tf_result
  until: tf_result | succeeded
  retries: "{{ tf_retries }}"
  delay: "{{ tf_delay }}"
