---
- include: each-cluster-nodepool.yaml
  with_subelements:
    - "{{ kraken_config.clusters }}"
    - nodePools
  loop_control:
    loop_var: cluster_node_tuple
  when:
    - cluster_node_tuple.0.providerConfig.type == 'cloudinit'
    - cluster_node_tuple.1.bastionConfig is defined