---
- name: Generate bastion sshd service units
  set_fact:
    cloud_config: "{{ cloud_config | combine(new_data, recursive=True) }}"
  vars:
    sshd_unit: '{{ lookup("template", "units.sshd.part.jinja2") | from_yaml }}'
    units: "{{ cloud_config[cluster.name][node.name].units | default([]) + sshd_unit }}"
    new_data: '{{ { cluster.name: { node.name: { "units": units } } } }}'