---
- set_fact:
    cluster: "{{ cluster_node_tuple.0 }}"
    node: "{{ cluster_node_tuple.1 }}"

- name: Generate bastion units.sshd.part
  template:
    src: units.sshd.part.jinja2
    dest: "{{ config_base }}/{{ cluster.name }}/{{ node.name }}.units.sshd.part"
