---
- name: Make sure generated folder for certs is there
  file:
    path: "{{ config_base }}/{{ cluster.name }}/certs"
    state: directory

- name: Generate self-signed CA key
  command: >
    openssl genrsa -out {{ config_base }}/{{ cluster.name }}/certs/ca-key.pem 2048
  args:
    creates: "{{ config_base }}/{{ cluster.name }}/certs/ca-key.pem"

- name: Generate self-signed CA
  command: >
    openssl req -x509 -new -nodes
      -key {{ config_base }}/{{ cluster.name }}/certs/ca-key.pem
      -days 7300
      -out {{ config_base }}/{{ cluster.name }}/certs/ca.pem
      -subj {{ (cluster.kubeAuth.authz.rbac is defined) | ternary("/O=system:masters/CN=kraken-ca","/CN=kraken-ca") }}
  args:
    creates: "{{ config_base }}/{{ cluster.name }}/certs/ca.pem"

- name: Generate certificate authority write_files
  include: cloud_config/write_files.yaml
  with_items:
    - write_files.cert-authority.part.jinja2
  when: node.bastionConfig is not defined