---
- name: Set Cluster Fact
  set_fact:
    cluster: "{{ a_cluster }}"

- name: Make sure generated folder for cloud init snippets is there
  file:
    path: "{{ config_base | expanduser }}/{{ cluster.name }}"
    state: directory

- name: rkt-install.yaml
  debug:
    var: nodepool
  with_items:
    - "{{ cluster.nodePools }}"
  loop_control:
    loop_var: nodepool
  when: nodepool.osConfig.distro == 'ubuntu'

- include: rkt-install.yaml
  with_items:
    - "{{ cluster.nodePools }}"
  loop_control:
    loop_var: nodepool
  when: nodepool.osConfig.distro == 'ubuntu'

- fail:
- include: network_environment.yaml
- include: certificate_authority.yaml
- include: os_update.yaml
- include: storage.yaml
- include: locksmith.yaml
- include: docker-install.yaml
- include: docker-wait-for-mounts.yaml
