- name: Generate etcd .units.exec-docker.part files
  template: src=docker-exec.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/etcd.{{item.name}}.units.exec-docker.part"
  with_items: "{{kraken_config.etcd}}"

- name: Generate master .units.exec-docker.part files
  template: src=docker-exec.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/master.units.exec-docker.part"
  with_items: ["{{kraken_config.master}}"]

- name: Generate node .units.exec-docker.part files
  template: src=docker-exec.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/node.{{item.name}}.units.exec-docker.part"
  with_items: "{{kraken_config.node}}"

- name: Generate etcd .units.exec-containerd.part files
  template: src=containerd-exec.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/etcd.{{item.name}}.units.exec-containerd.part" 
  with_items: "{{kraken_config.etcd}}"

- name: Generate master .units.exec-containerd.part files
  template: src=containerd-exec.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/master.units.exec-containerd.part"
  with_items: ["{{kraken_config.master}}"]

- name: Generate node .units.exec-containerd.part files
  template: src=containerd-exec.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/node.{{item.name}}.units.exec-containerd.part"
  with_items: "{{kraken_config.node}}"

- name: Generate etcd .units.docker-install.part files
  template: src=docker-install.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/etcd.{{item.name}}.units.docker-install.part"
  with_items: "{{kraken_config.etcd}}"

- name: Generate master .units.docker-install.part files
  template: src=docker-install.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/master.units.docker-install.part"
  with_items: ["{{kraken_config.master}}"]

- name: Generate node .units.docker-install.part files
  template: src=docker-install.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/node.{{item.name}}.units.docker-install.part"
  with_items: "{{kraken_config.node}}"
