---
- name: "Generate containerd, docker, and docker-install service units"
  set_fact:
    cloud_config: "{{ cloud_config | combine(new_data, recursive=True) }}"
  vars:
    dockerd_unit: "{{ lookup('template','docker-exec.part.jinja2') | from_yaml }}"
    containerd_unit: "{{ lookup('template','containerd-exec.part.jinja2') | from_yaml }}"
    docker_install_unit: "{{ lookup('template','docker-install.part.jinja2') | from_yaml }}"
    coreos: "{{ cloud_config[cluster.name][node.name].coreos | default({}) }}"
    units: "{{ coreos.units | default([]) + dockerd_unit + containerd_unit + docker_install_unit }}"
    new_data: '{{ { cluster.name: { node.name: { "coreos": { "units": units } } } } }}'
  when:
    - node.containerConfig.runtime == "docker"
    - node.containerConfig.type == "tgz"
