---
- name: "Generate containerd, docker, and docker-install service units" 
  set_fact:
    cloud_config: "{{ cloud_config | combine(new_data, recursive=True) }}"
  vars:
    dockerd_unit:
      "{{ lookup('template','docker-exec.part.jinja2') | from_yaml }}"
    containerd_unit:
      "{{ lookup('template','containerd-exec.part.jinja2') | from_yaml }}"
    docker_install_unit:
      "{{ lookup('template','docker-install.part.jinja2') | from_yaml }}"
    units: "{{ cloud_config[cluster.name][node.name].units | default([]) + dockerd_unit + containerd_unit + docker_install_unit }}"
    new_data: '{{ { cluster.name: { node.name: { "units": units } } } }}'
  when:
    - node.containerConfig.runtime == "docker"
    - node.containerConfig.type == "tgz"

- name: "DEBUG::: [post] docker-install.yaml"
  debug:
    var: cloud_config
