---
- name: "Generate docker-wait-for-mounts unit" 
  set_fact:
    cloud_config: "{{ cloud_config | combine(new_data, recursive=True) }}"
  vars:
    unit: "{{ lookup('template','docker-wait-for-mounts.part.jinja2') | from_yaml }}"
    coreos: "{{ cloud_config[cluster.name][node.name].coreos | default({}) }}"
    units: "{{ coreos.units | default([]) + unit }}"
    new_data: '{{ { cluster.name: { node.name: { "coreos": { "units": units } } } } }}'
  when:
    - node.nodeConfig.mounts is defined
    - node.containerConfig is defined