---
- name: Generate locksmith entry for {{ node.name }}
  set_fact:
    cloud_config: "{{ cloud_config | default({}) | combine(new_cloud_config, recursive=true) }}"
  vars:
    query: "clusters[?name == '{{ cluster.name }}'] | [0].nodePools[?name == 'etcd'] | [0]"
    etcd: "{{ kraken_config | json_query(query) }}"
    locksmith_data:
      endpoint: "{{ etcd.etcdConfig.ssl | ternary('https', 'http') }}://{{ etcd.name }}.{{ cluster.name }}.internal:{{ etcd.etcdConfig.clientPorts[0] }}"
      etcd_cafile: /etc/etcd/ssl/client-ca.pem
      etcd_certfile: /etc/etcd/ssl/client.pem
      etcd_keyfile: /etc/etcd/ssl/client-key.pem
    new_cloud_config: '{{ { cluster.name: { node.name: { "locksmith": locksmith_data } } } }}'
