---
- name: Generate nodePool .locksmith.part files
  template: src=locksmith.part.jinja2
            dest="{{ config_base | expanduser }}/{{ cluster.name }}/{{ item.name }}.locksmith.part"
  with_items: "{{ cluster.nodePools }}"
