---
- name: "Generate locksmith cloud_config settings"
  set_fact:
    cloud_config: "{{ cloud_config | combine(new_data, recursive=True) }}"
  vars:
    locksmith_data:
      "{{ lookup('template','locksmith.part.jinja2') | from_yaml }}"
    new_data: '{{ { cluster.name: { node.name: { "locksmith": locksmith_data } } } }}'
  when: node.osConfig.locksmith is defined