---
- name: "Generate locksmith cloud_config settings"
  set_fact:
    cloud_config: "{{ cloud_config | combine(new_data, recursive=True) }}"
  vars:
    data:
      coreos:
        "{{ lookup('template','locksmith.part.jinja2') | from_yaml }}"
    new_data: '{{ { cluster.name: { node.name: data } } }}'
  when: node.osConfig.locksmith is defined