---
- name: Loop over all elements of cluster_common for each cluster
  include: cluster-start.yaml
  with_subelements:
    - "{{ kraken_config.clusters }}"
    - nodePools
  loop_control:
    loop_var: cluster_node_tuple
  when: cluster_node_tuple.0.providerConfig.type == 'cloudinit'

- name: Generate shell command help text
  template:
    src: templates/help.txt.jinja2
    dest: "{{ config_base | expanduser }}/help.txt"
