---
- name: Generate network service file for {{ node.name }}
  set_fact:
    cloud_config: "{{ cloud_config | default({}) | combine(new_cloud_config, recursive=true) }}"
  vars:
    new_files:
      - path: /etc/systemd/system/kraken-networking.service
        content: |
          [Unit]
          Description=Setup Network Environment
          Requires=network-online.target
          After=network-online.target
          [Service]
          RemainAfterExit=yes
          Type=oneshot
          ExecStart=/opt/cnct/rkt/rkt run \
           --insecure-options=image \
           --net=host \
           --inherit-env=true \
           --volume etc,kind=host,source=/etc,readOnly=false \
           --mount volume=etc,target=/etc \
           quay.io/samsung_cnct/setup-network-environment:v1.0.1-mv
          ExecStopPost=/opt/cnct/rkt/rkt gc --mark-only
    write_files: "{{ cloud_config[cluster.name][node.name].write_files | default([]) }}"
    new_cloud_config: '{{ { cluster.name: { node.name: { "write_files": write_files + new_files }}} }}'

- name: Generate networking systemd unit for {{ node.name }}
  set_fact:
    cloud_config: "{{ cloud_config | default({}) | combine(new_cloud_config, recursive=true) }}"
  vars:
    new_runcmd:
      - [ systemctl, enable, kraken-networking ]
      - [ systemctl, start, --no-block, kraken-networking ]
    runcmd: "{{ cloud_config[cluster.name][node.name].runcmd | default([]) }}"
    new_cloud_config: '{{ { cluster.name: { node.name: { "runcmd": runcmd + new_runcmd }}} }}'
