---
- name: Generate per nodePool setup-network-environment.part files
  template: src=setup-network-environment.part.jinja2
            dest="{{ config_base | expanduser }}/{{ kraken_config.cluster }}/{{ item.name }}.units.setup-network-environment.part"
  with_items: "{{ cluster.nodePools }}"