---
- name: Generate etcd .coreos.update.part files
  template: src=os.update.part.jinja2
            dest="{{ config_base | expanduser }}/{{ cluster.name }}/etcd.{{ item.name }}.update.part"
  with_items: "{{ cluster.nodePools }}"
  when: item.etcdConfig is defined

- name: Generate master .coreos.update.part files
  template: src=os.update.part.jinja2
            dest="{{ config_base | expanduser }}/{{ cluster.name }}/master.update.part"
  with_items: "{{ cluster.nodePools }}"
  when: item.etcdConfig is not defined and item.name == "master"

- name: Generate node .coreos.update.part files
  template: src=os.update.part.jinja2
            dest="{{ config_base | expanduser }}/{{ cluster.name }}/node.{{ item.name }}.update.part"
  with_items: "{{ cluster.nodePools }}"
  when: item.etcdConfig is not defined and item.name != "master"