---
- name: Generate coreos update cloud_config setting for {{ node.name }}
  set_fact:
    cloud_config: "{{ cloud_config | default({}) | combine(new_cloud_config, recursive=true) }}"
  vars:
    entry:
      update:
        group: "{{ node.osConfig.channel | default('') }}"
        reboot-strategy: etcd-lock
    new_cloud_config: '{{ { cluster.name: { node.name: entry }} }}'
