---
- name: Generate CoreOS update cloud_config keys
  set_fact:
    cloud_config: "{{ cloud_config | combine(new_data, recursive=True) }}"
  vars:
    data:
      coreos:
        locksmith:
          group: "{{ node.osConfig.channel }}"
        update:
          "reboot-strategy": "{{ node.osConfig.rebootStrategy }}"
    new_data: '{{ { cluster.name: { node.name: data } } }}'