---
- name: Add cluster and nodepool to cloud_config
  set_fact:
    cloud_config: "{{ cloud_config | default({}) | combine(cluster_cloud_config_string | from_yaml, recursive=true) }}"
  vars:
    cluster_cloud_config_string: |
      {{ cluster.name }}:
        {{ nodepool.name }}: {}

- name: Add bootcmd to install rkt for {{ nodepool.name }}
  set_fact:
    cloud_config: "{{ cloud_config | default({}) | combine(new_cloud_config, recursive=true) }}"
  vars:
    rkt_ver: v1.25.0
    command:
      - "mkdir -p /opt/cnct && wget -qO- https://github.com/rkt/rkt/releases/download/{{ rkt_ver }}/rkt-{{ rkt_ver }}.tar.gz | tar -C /opt/cnct -xzf - && ln -sf /opt/cnct/rkt-{{ rkt_ver }}/rkt /usr/bin/"
    bootcmds: "{{ cloud_config[cluster.name][nodepool.name].bootcmd | default([]) }}"
    new_cloud_config: '{{ { cluster.name: { nodepool.name: { "bootcmd": bootcmds + command }}} }}'
