---
- name: "Generate common docker service units"
  include: cloud_config/units.yaml
  with_items:
    - containerd-exec.part.jinja2
    - docker-exec.part.jinja2
    - docker-install.part.jinja2
    - docker-wait-for-mounts.part.jinja2
  when:
    - node.containerConfig.runtime == "docker"
    - node.containerConfig.type == "tgz"

- name: "Generate network-environment service units"
  include: cloud_config/units.yaml
  with_items:
    - setup-network-environment.part.jinja2
  when: node.bastionConfig is not defined

- name: Create disk units
  include: disk_units.yaml
  with_items: "{{ node.nodeConfig.mounts }}"
  loop_control:
    loop_var: mount
  when: node.nodeConfig.mounts is defined