---
- name: Generate etcd .units.etcd.part files
  template: src=etcd.units.etcd.part.jinja2
            dest="{{ config_base | expanduser }}/{{ item.0.name }}/etcd.{{ item.1.name }}.units.etcd.part"
  with_subelements:
    - "{{ kraken_config.clusters }}"
    - nodePools
  when: item.1.etcdConfig is defined

- name: Generate kraken-ssl .units.etcd.part files
  template: src=etcd.units.kraken-etcd-ssl.part.jinja2
            dest="{{ config_base | expanduser }}/{{ item.0.name }}/etcd.{{ item.1.name }}.units.kraken-etcd-ssl.part"
  with_subelements:
    - "{{ kraken_config.clusters }}"
    - nodePools
  when: item.1.etcdConfig is defined
