---
- name: Generate etcd .units.etcd.part files
  template: src=etcd.units.etcd.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/etcd.{{item.name}}.units.etcd.part"
  with_items: "{{kraken_config.etcd}}"

- name: Generate kraken-ssl .units.etcd.part files
  template: src=etcd.units.kraken-etcd-ssl.part.jinja2
            dest="{{ config_base | expanduser }}/{{kraken_config.cluster}}/etcd.{{item.name}}.units.kraken-etcd-ssl.part"
  with_items: "{{kraken_config.etcd}}"