---
version: v1
definitions:
  ...
  helmConfigs:
    - &defaultHelm
      name: defaultHelm
      kind: helm
      repos:
        - name: atlas
          url: http://atlas.cnct.io
        - name: stable
          url: https://kubernetes-charts.storage.googleapis.com
      charts:
      - name: openldap
        repo: atlas
        chart: openldap
        version: 0.1.0
        namespace: kube-auth
        values:
          OpenLdap:
            Domain: local.io
            AdminPassword: admin
      -
        name: dex
        repo: atlas
        chart: dex
        version: 0.1.0
        namespace: kube-auth
        values:
          Dex:
            Issuer: https://auth.keyolk.cluster.io:30443
            StaticPassword:
              Email: "admin@example.com"
              Password: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
              Username: "admin"
              UserID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
            Connector:
              GitHub:
                Name: "GitHub"
                ClientId: ODAyOWM3MWNiYjRmNmFkOGZmZGE=
                ClientSecret: NTE5YzRlODg0NDI3MTBhZDJmMGM0YWE1NDBjNjgyZTNlNDY4YWEzZg==
              Oidc:
                Issuer: https://accounts.google.com
                ClientId: ODc2MDc2NjM5NDQ0LW8zdTIzZjY5ZGlsdXMxYTBkNzd0ZHQxb3FzMWZpaDViLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
                ClientSecret: T0pMc0FLeUpsY2ZjaUtnbkhzaHVwZjQ4
              Ldap:
                Name: "LDAP"
                Host: "openldap:389"
                InsecureNoSsl: true
                InsecureSkipVerify: true
                BindDn: "cn=admin,dc=local,dc=io"
                BindPw: "admin"
                UserSearch:
                  BaseDn: "ou=users,dc=local,dc=io"
                  Filter: "(objectClass=posixAccount)"
                  Username: "uid"
                  IdAttr: "uid"
                  EmailAttr: "mail"
                  NameAttr: "uid"
                GroupSearch:
                  BaseDn: "ou=groups,dc=local,dc=io"
                  Filter: "(objectClass=posixGroup)"
                  UserAttr: "uid"
                  GroupAttr: "memberUid"
                  NameAttr: "cn"
          DexApp:
            RedirectUri: http://auth.keyolk.cluster.io:30080/callback
  kubeAuth:
   - &defaultKubeAuth
    authn:
      oidc:
        service_name: dex
      default_basic_user: admin
      basic:
      - user: admin
        password: secret
    authz:
      rbac: {}
