---
explicit_aws_access_key: "{{ kraken_config.providerConfig.authentication.accessKey }}"
credentials_aws_access_key: "{{ lookup('ini', 'aws_access_key_id section='+kraken_config.providerConfig.authentication.credentialsProfile+' file='+kraken_config.providerConfig.authentication.credentialsFile) }}"
aws_access_key: "{{ (explicit_aws_access_key == '') | ternary(credentials_aws_access_key,explicit_aws_access_key) }}"
explicit_aws_secret_key: "{{ kraken_config.providerConfig.authentication.accessSecret }}"
credentials_aws_secret_key: "{{ lookup('ini', 'aws_secret_access_key section='+kraken_config.providerConfig.authentication.credentialsProfile+' file='+kraken_config.providerConfig.authentication.credentialsFile) }}"
aws_secret_key: "{{ (explicit_aws_secret_key == '') | ternary(credentials_aws_secret_key,explicit_aws_secret_key) }}"
