---
- name: rename cluster fact
  set_fact:
    cluster: "{{ a_cluster }}"

# because BOTO2 doesn't support AWS_SHARED_CREDENTIALS_FILE environment variable, do some mangling
- include: aws_config.yaml
  when: cluster.providerConfig.provider == 'aws'

- include: aws_ssh_config.yaml

- include: aws_bastion_ssh_config.yaml
  when:  bastion_results.instances | length > 0
