---
- name: Set cluster fact
  set_fact:
    cluster: "{{ a_cluster }}"

- name: Set facts for creating storage class
  set_fact:
    kubectl: "/opt/cnct/kubernetes/{{ kubernetes_minor_versions[cluster.name] }}/bin/kubectl"
    kubeconfig: "{{ config_base }}/{{ cluster.name }}/admin.kubeconfig"

- name: Create storage class for aws
  command: >
    {{ kubectl }} --kubeconfig={{ kubeconfig }} apply -f "{{ item }}"
  with_first_found:
    - files:
      - /kraken/ansible/roles/kraken.services/files/{{ cluster.providerConfig.provider }}/storage-class-config.yaml
      skip: true