---
- name: Collect all services
  command: >
    kubectl --kubeconfig={{ kubeconfig }} get services --all-namespaces -o json
  register: added_services
  when: kraken_action == 'down'
  ignore_errors: yes

- name: Register services fact
  set_fact:
    added_services_map: "{{ added_services.stdout|from_json }}"
  when: kraken_action == 'down'
  ignore_errors: yes

- name: Set services info
  set_fact:
    the_services: "{{ added_services_map.items()[0][1] }}"
  when: kraken_action == 'down'
  ignore_errors: yes

- name: Clean up releases
  command: >
    helm delete --purge {{ item.name }}
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
    HELM_HOME: "{{ helm_home }}"
  with_items: "{{cluster_services}}"
  ignore_errors: yes
  when: tiller_present|success

- name: Clean up tiller if present
  command: >
    kubectl --kubeconfig={{ kubeconfig }} delete deployment {{ tiller }} --namespace=kube-system
  when: tiller_present|success

- name: Clean up services
  command: >
    kubectl --kubeconfig={{ kubeconfig }} delete --namespace {{ item.metadata.namespace }} svc {{ item.metadata.name }} --grace-period=600
  with_items: "{{ the_services }}"
  when: item.status.loadBalancer.ingress[0].hostname is defined and kraken_action == 'down'
  ignore_errors: yes

- name: Delete all service namespaces
  command: >
    kubectl --kubeconfig={{ kubeconfig }} delete namespace {{ item }}
  with_items: "{{ cluster_namespaces }}"
  when: cluster_namespaces is defined
  ignore_errors: yes

- name: Get vpc id
  shell: "terraform state show -state={{ config_base | expanduser }}/{{kraken_config.cluster}}/terraform.tfstate module.vpc.aws_vpc.vpc  | awk '/^id/{print $3}'"
  register: vpcid
  when: kraken_action == 'down'
  changed_when: false

- name: Set vpcid lookup string
  set_fact:
    vpc_lookup: "elbs[?vpc_id=='{{ vpcid.stdout }}']"
  when: kraken_action == 'down'
  changed_when: false

- name: Wait for ELBs to be deleted
  action:
    module: ec2_elb_facts
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ kraken_config.providerConfig.region  }}"
  register: elb_facts
  vars:
    vpc_lookup: "elbs[?vpc_id=='{{ vpcid.stdout }}']"
  when: kraken_action == 'down'
  until: "{{ elb_facts|json_query(vpc_lookup)|length }} <= 1"
  retries: 600
  delay: 1
