---
- set_fact:
    kubeconfig: "{{ config_base | expanduser }}/{{ cluster.name }}/admin.kubeconfig"

- name: Clean up DNS
  command: >
    kubectl --kubeconfig={{ kubeconfig }} delete -f {{ config_base | expanduser }}/{{ cluster.name }}/services/dns-deployment.yaml --namespace={{ dns_config.namespace }}
  when: kraken_action == 'down'
  ignore_errors: yes
