---
- set_fact:
    cluster: "{{ a_cluster }}"

- set_fact:
    kubeconfig: "{{ config_base | expanduser }}/{{ cluster.name }}/admin.kubeconfig"

- name: Merge User DNS Config with Default DNS Config
  set_fact:
    dns_config: "{{ kubedns | combine(cluster.dnsConfig.kubedns) | expand_config }}"

- debug:
    var: dns_config.namespace

- name: Clean up DNS
  command: >
    kubectl --kubeconfig={{ kubeconfig }} delete -f {{ config_base | expanduser }}/{{ cluster.name }}/services/dns-deployment.yaml --namespace={{ dns_config.namespace }}
  when: kraken_action == 'down'
  ignore_errors: yes
