---
- name: Clean up DNS
  command: >
    kubectl --kubeconfig={{ kubeconfig }} delete -f {{ config_base | expanduser }}/{{ kraken_config.cluster }}/services/dns-deployment.yaml --namespace={{ dns_config.namespace }}
  when: kraken_action == 'down'
  ignore_errors: yes
