---
- set_fact:
    kubeconfig: "{{ config_base | expanduser }}/{{ cluster.name }}/admin.kubeconfig"

- name: Make sure generated folder for services is there
  file: >
    path="{{ config_base | expanduser }}/{{ cluster.name }}/services"
    state=directory

- debug:
    var: kubernetes_minor_versions[ cluster.name ]

- name: Create the DNS Service Deployment
  template: src="{{ item }}"
    dest="{{ config_base | expanduser }}/{{ cluster.name }}/services/dns-deployment.yaml"
  with_first_found:
    - files:
      - "{{ kubernetes_minor_versions[ cluster.name ] }}/dns.yaml.jinja2"
      - dns.yaml.jinja2

- name: Wait for api server to become available in case it is not already
  wait_for:
    host: "{{ item | regex_replace('https://','') }}"
    port: 443
    timeout: 600
  with_items: "{{ api_servers }}"

- name: Install DNS
  command: >
      kubectl --kubeconfig={{ kubeconfig | expanduser }} apply -f {{ config_base | expanduser }}/{{ cluster.name }}/services/dns-deployment.yaml 
  register: deployment_dns_result

