- name: Generate master api-server.yaml
  template: src=api-server-manifest.yaml.jinja2
    dest="{{ config_base | expanduser }}/{{ item.0.name }}/master.api-server.yaml.manifest"

- name: Generate master controller-manager.yaml
  template: src=controller-manager-manifest.yaml.jinja2
    dest="{{ config_base | expanduser }}/{{ item.0.name }}/master.controller-manager.yaml.manifest"

- name: Generate master kube-proxy.yaml
  template: src=kube-proxy-manifest.yaml.jinja2
    dest="{{ config_base | expanduser }}/{{ item.0.name }}/master.kube-proxy.yaml.manifest"

- name: Generate master scheduler.yaml
  template: src=scheduler-manifest.yaml.jinja2
    dest="{{ config_base | expanduser }}/{{ item.0.name }}/master.scheduler.yaml.manifest"
