---
- set_fact:
    cluster: "{{ cluster_node_tuple.0 }}"
    node: "{{ cluster_node_tuple.1 }}"

- name: Generate node units.kraken-worker-ssl.part
  template: src=units.kraken-worker-ssl.part.jinja2
    dest="{{ config_base | expanduser }}/{{ cluster.name }}/{{ node.name }}.units.kraken-worker-ssl.part"

- name: Generate node units.kubelet.part
  template:
    src: "{{ item }}"
    dest: "{{ config_base | expanduser }}/{{ cluster.name }}/{{ node.name }}.units.kubelet.part"
  with_first_found:
    - files:
      - "{{ kubernetes_minor_versions[ cluster.name ] }}/units.kubelet.part.jinja2"
      - units.kubelet.part.jinja2
