---

- name: AWS update
  include_role:
    name: '{{ playbook_dir }}/roles/kraken.update/kraken.update.aws'
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when: a_cluster.providerConfig.provider == 'aws'

- name: GKE update
  include_role:
    name: '{{ playbook_dir }}/roles/kraken.update/kraken.update.gke'
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when: a_cluster.providerConfig.provider == 'gke'

- name: Error Provider
  include_role:
    name: '{{ playbook_dir }}/roles/kraken.error'
    kraken_component_type: provider
    kraken_component_error: 'Unsupported provider'
    kraken_component_name: '{{ a_cluster.providerConfig.provider }}'
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when: a_cluster.providerConfig.provider not in ['aws', 'gke']
