---
- include: service-account-key.yaml
  with_subelements:
    - "{{ kraken_config.clusters }}"
    - nodePools
  loop_control:
    loop_var: cluster_node_tuple
  when: cluster_node_tuple.1.apiServerConfig is defined
        and cluster_node_tuple.0.providerConfig.type == 'cloudinit'

- include: render-manifests.yaml
  with_subelements:
    - "{{ kraken_config.clusters }}"
    - nodePools
  loop_control:
    loop_var: cluster_node_tuple
  when: cluster_node_tuple.1.apiServerConfig is defined
        and cluster_node_tuple.0.providerConfig.type == 'cloudinit'

- include: render-kubeconfig.yaml
  with_subelements:
    - "{{ kraken_config.clusters }}"
    - nodePools
  loop_control:
    loop_var: cluster_node_tuple
  when: cluster_node_tuple.1.apiServerConfig is defined
        and cluster_node_tuple.0.providerConfig.type == 'cloudinit'

- include: render-write-files.yaml
  with_subelements:
    - "{{ kraken_config.clusters }}"
    - nodePools
  loop_control:
    loop_var: cluster_node_tuple
  when: cluster_node_tuple.1.apiServerConfig is defined
        and cluster_node_tuple.0.providerConfig.type == 'cloudinit'

- include: render-units.yaml
  with_subelements:
    - "{{ kraken_config.clusters }}"
    - nodePools
  loop_control:
    loop_var: cluster_node_tuple
  when: cluster_node_tuple.1.apiServerConfig is defined
        and cluster_node_tuple.0.providerConfig.type == 'cloudinit'
