---
- set_fact:
    cluster: "{{ cluster_node_tuple.0 }}"
    node: "{{ cluster_node_tuple.1 }}"

- name: Generate master kubelet kubeconfig
  template: src=kubeconfig.jinja2
    dest="{{ config_base | expanduser }}/{{ cluster.name }}/{{ node.name }}.kubeconfig.manifest"
