---
- name: Generate master basc auth csv by kube version
  template:
    src: "{{ item }}"
    dest: "{{ config_base }}/{{ cluster.name }}/basicauth.csv"
  with_first_found:
    - files:
      - "{{ kubernetes_minor_versions[ cluster.name ] }}/basicauth.csv.jinja2"
      - basicauth.csv.jinja2
  when: (cluster.kubeAuth.authn.basic is defined)

- name: Generate master writefiles basicauth
  template: src=write_files.basicauth.part.jinja2
    dest="{{ config_base }}/{{ cluster.name }}/{{ node.name }}.write_files.basicauth.part"
  when: (cluster.kubeAuth.authn.basic is defined)

- name: Generate master writefiles service account pem
  template: src=write_files.serviceaccount.part.jinja2
    dest="{{ config_base | expanduser }}/{{ cluster.name }}/{{ node.name }}.write_files.serviceaccount.part"