---
- name: "Generate master kubelet and apiserver service units"
  set_fact:
    cloud_config: "{{ cloud_config | combine(new_data, recursive=True) }}"
  vars:
    template_name: units.kubelet.part.jinja2
    versioned_template: "{{ kubernetes_minor_versions[ cluster.name ] }}/{{ template_name }}"
    unit_template: "{{ (versioned_template | is_file) | ternary(versioned_template, template_name) }}"
    content: "{{ lookup('template',write_file_template) }}"
    write_files: "{{ cloud_config[cluster.name][node.name].write_files | default([]) + write_file }}"
    kubelet_unit: "{{ lookup('template', unit_template) | from_yaml }}"
    apiserver_unit: '{{ lookup("template", "units.kraken-apiserver-ssl.part.jinja2") | from_yaml }}'
    coreos: "{{ cloud_config[cluster.name][node.name].coreos | default({}) }}"
    units: "{{ coreos.units | default([]) + kubelet_unit + apiserver_unit }}"
    new_data: '{{ { cluster.name: { node.name: { "coreos": { "units": units } } } } }}'
