---
- name: Make sure generated folder for generated key is there
  file:
    path: "{{ config_base }}/{{ cluster.name }}/certs"
    state: directory

- name: Generate ServiceAccount key
  openssl_privatekey:
    path: "{{ config_base | expanduser }}/{{ cluster.name }}/certs/service-account.pem"
    size: 2048

- name: Extract ServiceAccount public key
  openssl_publickey:
    privatekey_path: "{{ config_base | expanduser }}/{{ cluster.name }}/certs/service-account.pem"
    path: "{{ config_base | expanduser }}/{{ cluster.name }}/certs/service-account-pub.pem"

- name: Generate master serviceAccount pem write_files
  set_fact:
    cloud_config: "{{ cloud_config | combine(new_data, recursive=True) }}"
  vars:
    write_file:
      - path: /etc/kubernetes/ssl/service-account-key.pem
        encoding: "gz+b64"
        content: "{{ lookup('file', '{{config_base}}/{{ cluster.name }}/certs/service-account.pem' | expanduser) | gz | b64encode }}"
    write_files: "{{ cloud_config[cluster.name][node.name].write_files | default([]) + write_file }}"
    new_data: '{{ { cluster.name: { node.name: { "write_files": write_files } } } }}'