---
- name: Make sure generated folder for generated key is there
  file:
    path: "{{ config_base }}/{{ cluster.name }}/certs"
    state: directory

- name: Generate self-signed service account key
  command: >
    openssl genrsa -out {{ config_base }}/{{ cluster.name }}/certs/service-account.pem 2048
  args:
    creates: "{{ config_base }}/{{ cluster.name }}/certs/service-account.pem"

- name: Extract service account public key
  command: >
    openssl rsa -in {{ config_base }}/{{ cluster.name }}/certs/service-account.pem
      -outform PEM -pubout -out {{ config_base }}/{{ cluster.name }}/certs/service-account-pub.pem
  args:
    creates: "{{ config_base }}/{{ cluster.name }}/certs/service-account-pub.pem"