- set_fact:
    cluster: "{{ item }}"

- name: Look up and set k8s minor version for this cluster
  set_fact:
    kubernetes_minor_version: "{{ kubernetes_minor_versions[cluster.name] }}"

- name: Set helm override env variable key to contain the cluster name
  set_fact:
    helm_override_key: "HELM_OVERRIDE_{{cluster.name}}"

- name: Get helm override environment variable
  set_fact:
    HELM_OVERRIDE: "{{ lookup('env', helm_override_key) }}"

- name: Set helm_available to true for k8s 1.4 and 1.5
  set_fact:
    helm_available: true
  when: (kubernetes_minor_version == 'v1.4') and (kubernetes_minor_version == 'v1.5') and (kubernetes_minor_version == 'v1.6')

- name: Set helm_available false for unsupported k8s version
  set_fact:
    helm_available: false
  when: kubernetes_minor_version == 'v1.7'

- name: Stop and print out message if helm is not available and HELM_OVERRIDE has not been set
  fail:
    msg: "This version of Kubernetes does not currently have helm support. If you would like to continue without using helm, execute following command:
    export {{ helm_override_key }}=false && ./up.sh
    If you would like to use the latest version of helm instead, execute:
    export {{ helm_override_key }}=true && ./up.sh
    WARNING: You may have to specify your config file path if it is not located in the default path."
  when: helm_available == false and HELM_OVERRIDE == ""

- name: Keep track of helm overrides by cluster name
  set_fact:
    helm_overrides: "{{ helm_overrides | default({}) | combine
      (
        {cluster.name: HELM_OVERRIDE }
      )
    }}"
  when: HELM_OVERRIDE != ""

- name: Keep track of helm availability by cluster name
  set_fact:
    helm_availabilities: "{{ helm_availabilities | default({}) | combine
      (
        {cluster.name: helm_available }
      )
    }}"
