- name: Get oidc provider values from cluster services
  set_fact:
    oidc_provider_values: "{{ item.get('values') }}"
  with_items: "{{ kraken_config.clusterServices.services | default([]) }}"
  when: item.name == "{{ kraken_config.kubeAuth.oidc.service_name }}"

- name: Retrieve issuer URL
  set_fact: 
    oidc_issuer: "{{ oidc_provider_values.Dex.Issuer }}"

- name: Retrieve domain value from 
  shell: "echo {{ oidc_issuer  }} | awk -F/ '{print $3}' | awk -F: '{print $1}'"
  register: oidc_domain

- name: Set oidc values to kraken_config.kubeAuth
  set_fact:
    kraken_config: "{{ kraken_config | combine(
    {
      'kubeAuth':{
        'oidc':{
          'issuer': oidc_issuer,
          'domain': oidc_domain.stdout 
        }
      }
    } )}}"
