---
- name: Delete the deployment (cluster)
  command: >
    gcloud deployment-manager deployments delete {{ cluster.name }}-k2-deployment
      --project {{ cluster.providerConfig.project }}
      --no-async
      --quiet
  ignore_errors: yes

- name: Query all clusters
  shell: gcloud container clusters list --project {{ cluster.providerConfig.project }} --filter='name:{{ cluster.name }}' --format='value(name)'
  register: cluster_check
  ignore_errors: yes

- name: Delete the cluster
  command: >
    gcloud container clusters delete {{ cluster.name }}
      --project {{ cluster.providerConfig.project }}
      --zone {{ cluster.providerConfig.zone.primaryZone }}
      --no-async
      --quiet
  when: cluster_check.stdout == cluster.name
