---
- name: rename cluster fact
  set_fact:
    cluster: "{{ a_cluster }}"

- include: authenticate.yaml
- include: process-cluster.yaml
  when: kraken_action == 'up'
- include: destroy-cluster.yaml
  when: kraken_action == 'down'
- include: deauthenticate.yaml