---
- name: rename cluster fact
  set_fact:
    cluster: "{{ a_cluster }}"

- name: Make sure generated folder for full cloud configs is there
  file:
    path: "{{ config_base | expanduser }}/{{ cluster.name }}"
    state: directory
    
- name: Render a deployment manager template for created-cluster.yaml in advance
  template: src=deploymentmanager-create.yaml.jinja2
   dest="{{ config_base | expanduser }}/{{ cluster.name }}/deploymentmanager-create.yaml"

- include: authenticate.yaml
  when: not ( dryrun | bool )
- include: process-cluster.yaml
  when: kraken_action == 'up' and not ( dryrun | bool )
- include: destroy-cluster.yaml
  when: kraken_action == 'down' and not ( dryrun | bool )
- include: deauthenticate.yaml
  when: not ( dryrun | bool )
