- set_fact:
    cluster: "{{ a_cluster }}"

- name: Look up and set k8s minor version for this cluster
  set_fact:
    kubernetes_minor_version: "{{ kubernetes_minor_versions[cluster.name] }}"

- name: Execute appropriate kubectl per minor version
  set_fact:
    kubectl: "/opt/cnct/kubernetes/{{ kubernetes_minor_version }}/bin/kubectl"

- set_fact:
    aws_region: "{{ cluster.providerConfig.region }}"
    kubeconfig: "{{ config_base | expanduser }}/{{ cluster.name }}/admin.kubeconfig"

- name: Set Expected Cluster Node count
  vars:
    test_case: "nodePools[?name=='clusterNodes'].count"
  set_fact:
    expected_cluster_node_count: "{{ cluster | json_query(test_case) | first }}"

- debug:
    msg: "There should be 3 cluster nodes. Are there? {{ expected_cluster_node_count }}"

- name: Collect cluster nodes
  command: >
   {{ kubectl }} --kubeconfig={{ kubeconfig }} get nodes -l nodepool=clusterNodes -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}'
  register: cluster_node_names

- debug:
    msg: "Cluster node names: {{ cluster_node_names }}"

- name: Create dict with node names and instance ids
  set_fact:
    cluster_node_names_and_instance_ids: "{{ cluster_node_names_and_instance_ids | default({}) | combine( {item.0: item.1} ) }}"
  with_together:
    - "{{ instance_info.instances | map (attribute='private_dns_name') | list }}"
    - "{{ instance_info.instances | map(attribute='id') | list }}"
  when: item.0 in cluster_node_names.stdout_lines

- debug:
    msg: "Cluster node dict: {{ cluster_node_names_and_instance_ids }}"

- name: Set nodepool label
  set_fact:
    nodepool_label: "clusterNodes"

- name: Delete and Terminate Cluster Nodes
  set_fact:
    cluster_node_destruction: "{{ item.key | delete_and_terminate_node_filter(item.value, expected_cluster_node_count, kubeconfig, aws_region, nodepool_label) }}"
  with_dict: "{{ cluster_node_names_and_instance_ids }}"
  failed_when: cluster_node_destruction == False
