---
- debug:
    msg: nodePools
- include: aws-control-plane.yaml
  with_subelements:
    - "{{ kraken_config.clusters }}"
    - nodePools
  loop_control:
    loop_var: cluster_with_nodepool
  when: cluster_with_nodepool[1].name == "master" and upgrade_master_only

- name: STOP ALL THE THINGS
  set_fact:
    unicorns: "{{ kraken_config.unicorns }}"
