---
  
- name: Set list of nodepools to be upgraded
  set_fact:
    nodepools_to_upgrade: "{{ upgrade_nodepools.split(',') }}"

- include: upgrade-cluster.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
