---

- name: Set list of nodepools to be upgraded
  set_fact:
    nodepools_to_upgrade: "{{ upgrade_nodepools.split(',') }}"

- name: Fail when no nodepools were passed to upgrade
  fail:
    msg: "Argument empty. Please pass --nodepools <comma,separated,list,of,nodepools> to upgrade action."
  when: upgrade_nodepools == ""

- include: upgrade-cluster.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
