---

- name: Set list of nodepools to be upgraded
  set_fact:
    nodepools_to_upgrade: "{{ upgrade_nodepools.split(',') }}"

# TODO: use fail module when nodepools_to_upgrade is empty.

# - name: Do not allow multiple clusters in config
#   fail:
#     msg: "Multiple clusters are not yet supported in k2"
#   when: "{{ kraken_config.clusters | length | int > 1 }}"

- include: upgrade-cluster.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
