---
- name: Set cluster fact
  set_fact:
    cluster: "{{ a_cluster }}"

- name: Canal Fabric Type
  include_role:
    name: '{{ playbook_dir }}/roles/kraken.fabric/kraken.fabric.flannel'
  when: cluster.fabricConfig.type == 'canal'

- name: Weave Fabric Type
  include_role:
    name: '{{ playbook_dir }}/roles/kraken.fabric/kraken.fabric.weave'
  when: cluster.fabricConfig.type == 'weave'

- name: Check for a supported fabric type.
  include_role:
    name: '{{ playbook_dir }}/roles/kraken.error'
    kraken_component_type: type
    kraken_component_error: 'Unsupported fabric type'
  when: cluster.fabricConfig.type not in ['canal', 'weave']
