---
- hosts: localhost
  roles:
    - {
        role: 'kraken.config',
        tags: [ 'always', 'config_only' ]
      }
    - {
        role: 'roles/kraken.cluster_common',
        tags: [ 'assembler', 'provider', 'ssh', 'readiness', 'services', 'all', 'dryrun' ]
      }
    - {
        role: 'roles/kraken.nodePool/kraken.nodePool.selector',
        tags: [ 'assembler', 'provider', 'ssh', 'readiness', 'services', 'all', 'dryrun' ]
      }
    - {
        role: 'roles/kraken.assembler',
        tags: [ 'assembler', 'provider', 'ssh', 'readiness', 'services', 'all', 'dryrun' ]
      }
    - {
        role: 'roles/kraken.provider/kraken.provider.selector',
        tags: [ 'provider', 'ssh', 'readiness', 'services', 'all', 'dryrun']
      }
    - {
        role: 'roles/kraken.access',
        tags: [ 'readiness', 'services', 'all', 'dryrun', 'access_only' ]
      }
    - {
        role: 'roles/kraken.rbac',
        tags: [ 'readiness', 'services', 'all', 'dryrun', 'rbac_only' ]
      }
    - {
        role: 'roles/kraken.readiness',
        wait_for_all_hosts: false,
        tags: [ 'readiness', 'services', 'all' ]
      }
    - {
        role: 'roles/kraken.fabric/kraken.fabric.selector',
        tags: [ 'assembler', 'provider', 'ssh', 'readiness', 'services', 'all', 'dryrun', 'fabric_only' ]
      }
    - {
        role: 'roles/kraken.readiness',
        wait_for_all_hosts: true,
        tags: [ 'readiness', 'services', 'all', 'ssh_only' ]
      }
    - { # Run the SSH config generation when all nodes/ASGs are ready.
        role: 'roles/kraken.ssh/kraken.ssh.selector',
        tags: [ 'ssh', 'all', 'dryrun' ,'ssh_only' ]
      }
    - {
        role: 'roles/kraken.services',
        tags: [ 'services', 'services_only', 'all', 'dns_only' ]
      }
    - {
        role: 'roles/kraken.post',
        tags: [ 'all','provider','readiness','services','post_only' ]
      }
