---

- include: up.yaml

- hosts: localhost

  roles:
    - {
        role: '{{ playbook_dir }}/roles/kraken.update/kraken.update.selector',
        tags: [ 'provider', 'ssh', 'readiness', 'services', 'all', 'provider_only']
      }

    # - {
    #     role: '{{ playbook_dir }}/roles/kraken.update/kraken.update.aws',
    #     tags: [ 'readiness', 'services', 'all', 'readiness_only' ],
    #   }
