---
- hosts: localhost
  roles:
    - {
        role: 'kraken.config', config_file: "{{ config_path | default('') }}",
        tags: [ 'config', 'always', 'config_only' ]
      }
    - {
        role: 'kraken.nodePool/kraken.nodePool.selector',
        tags: [ 'master', 'assembler', 'provider', 'ssh', 'readiness', 'services', 'all', 'dryrun', 'master_ony' ]
      }
    - {
      role: 'kraken.upgrade/kraken.upgrade.aws',
      tags: [ 'readiness', 'services', 'all', 'readiness_only' ]
    }
