---
#
# expects:
#   cluster
#   kubeconfig
#
#   kubernetes_minor_versions
#   kraken_endpoint
#
- name: Look up and set k8s minor version for this cluster
  set_fact:
    kubernetes_minor_version: "{{ kubernetes_minor_versions[cluster.name] }}"

- name: Execute appropriate kubectl per minor version
  set_fact:
    kubectl: "/opt/cnct/kubernetes/{{ kubernetes_minor_version }}/bin/kubectl"

- name: create kubeconfig entry
  command: >
    {{ kubectl }} config set-cluster {{ cluster.name }}
      --server=https://{{ kraken_endpoint }}
      --certificate-authority={{ config_base | expanduser }}/{{ cluster.name }}/certs/ca.pem
      --embed-certs=true
      --kubeconfig={{ kubeconfig }}
  vars:
    kconfig: "{{ lookup('file',kubeconfig) | from_yaml }}"
    query: "clusters[?name=='{{ cluster.name }}'].cluster"
    ca_exists: "{{ (kconfig | json_query(query) | first)['certificate-authority-data'] is defined }}"
  when:
    - not ca_exists

- name: create admin user entry from basicauth user
  command: >
    {{ kubectl }} config set-credentials {{ cluster.name }}_admin
      --username={{ default_basic_kube_auth.user }}
      --password={{ default_basic_kube_auth.password }}
      --client-certificate={{ config_base | expanduser }}/{{ cluster.name }}/certs/end-user.crt
      --client-key={{ config_base | expanduser }}/{{ cluster.name }}/certs/end-user.key
      --embed-certs=true
      --kubeconfig={{ kubeconfig }}
  vars:
    kconfig: "{{ lookup('file',kubeconfig) | from_yaml }}"
    query: "users[?name=='{{ cluster.name }}_admin'].user"
    user_exists: "{{ (kconfig | json_query(query) | first)['username'] is defined }}"
    default_basic_kube_auth: "{{ cluster.kubeAuth.authn.basic | selectattr('user', 'match', '^'+cluster.kubeAuth.authn.default_basic_user+'$') | first }}"
  when:
    - cluster.kubeAuth.authn.basic is defined
    - cluster.kubeAuth.authn.cert is undefined
    - not user_exists

- name: create admin user entry from cert user
  command: >
    {{ kubectl }} config set-credentials {{ cluster.name }}_admin
      --username={{ default_cert_kube_auth.user }}
      --client-certificate={{ config_base | expanduser }}/{{ cluster.name }}/certs/end-user.crt
      --client-key={{ config_base | expanduser }}/{{ cluster.name }}/certs/end-user.key
      --embed-certs=true
      --kubeconfig={{ kubeconfig }}
  vars:
    kconfig: "{{ lookup('file',kubeconfig) | from_yaml }}"
    query: "users[?name=='{{ cluster.name }}_admin'].user"
    user_exists: "{{ (kconfig | json_query(query) | first)['username'] is defined }}"
    default_cert_kube_auth: "{{ cluster.kubeAuth.authn.cert | selectattr('user', 'match', '^'+cluster.kubeAuth.authn.default_basic_user+'$') | first }}"
  when:
    - cluster.kubeAuth.authn.cert is defined
    - not user_exists

- name: create context entry
  command: >
    {{ kubectl }} config set-context {{ cluster.name }}_context
      --cluster={{ cluster.name }}
      --user={{ cluster.name }}_admin
      --kubeconfig={{ kubeconfig }}
  vars:
    kconfig: "{{ lookup('file',kubeconfig) | from_yaml }}"
    query: "contexts[?name=='{{ cluster.name }}_context'].context"
    context_exists: "{{ (kconfig | json_query(query) | first)['cluster'] is defined }}"
  when:
    - not context_exists

- name: set current context
  command: >
    {{ kubectl }} config use-context {{ cluster.name }}_context
      --kubeconfig={{ kubeconfig }}
  vars:
    kconfig: "{{ lookup('file',kubeconfig) | from_yaml }}"
  when: kconfig.current-context is not defined or kconfig.current-context != "{{ cluster.name }}_context"
