---
- name: Fail when kraken_endpoint defined but empty
  fail:
    msg: >-
      Attempting to configure cluster {{ cluster.name }} and stopping because kraken_endpoint is not set.
  when: (kraken_endpoint is defined) and (kraken_endpoint == '')


- include: setup-certs.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when: a_cluster.providerConfig.type == 'cloudinit'
