---
#
# expects:
#    kubernetes_minor_versions
#    kraken_endpoint
#
- set_fact:
    cluster: "{{ a_cluster }}"
#
# certificate auth
#
- include: generate-user-cert-config.yaml
  with_items:
    - "{{ a_cluster.kubeAuth.authn.cert }}"
  loop_control:
    loop_var: a_user
  when: (kraken_endpoint is defined) and (a_cluster.kubeAuth.authn.cert is defined)
#
# reset kubeconfig path for the admin config generation
- name: Set kubeconfig path
  set_fact:
    kubeconfig: "{{ config_base | expanduser }}/{{ cluster.name }}/admin.kubeconfig"

- include: generate-admin-cert.yaml

- include: generate-admin-kubeconfig.yaml
  when: kraken_endpoint is defined



