---
- name: AWS provider
  include_role:
    name: '{{ playbook_dir }}/roles/kraken.provider/kraken.provider.aws'
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when: a_cluster.providerConfig.provider == 'aws'

- name: GKE provider
  include_role:
    name: '{{ playbook_dir }}/roles/kraken.provider/kraken.provider.gke'
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when: a_cluster.providerConfig.provider == 'gke'