---
- name: "Generate master kube-proxy manifest write_file"
  set_fact:
    cloud_config: "{{ cloud_config | combine(new_data, recursive=True) }}"
  vars:
    write_file:
      - path: /etc/kubernetes/manifests/kube-proxy.yaml
        owner: root
        permissions: 0644
        content: "{{ lookup('template', 'kube-proxy-manifest.yaml.jinja2') }}"
    write_files: "{{ cloud_config[cluster.name][node.name].write_files | default([]) + write_file }}"
    new_data: '{{ { cluster.name: { node.name: { "write_files": write_files } } } }}'