---
- set_fact:
    cluster: "{{ cluster_node_tuple.0 }}"
    node: "{{ cluster_node_tuple.1 }}"

- name: Generate node kube proxy.yaml
  template: src=kube-proxy-manifest.yaml.jinja2
    dest="{{ config_base | expanduser }}/{{ cluster.name }}/{{ node.name }}.kube-proxy.yaml.manifest"
