---

- name: Set list of nodepools to be updated
  set_fact:
    nodepools_to_update: "{{ update_nodepools.split(',') }}"

- name: Fail when no nodepools were passed to update
  fail:
    msg: "Argument empty. Please pass --nodepools <comma,separated,list,of,nodepools> to update action."
  when: update_nodepools == ""

- include: update-cluster.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
