---

- name: Set list of nodepools to be updated
  set_fact:
    nodepools_to_update: "{{ update_nodepools.split(',') }}"

- include: update-cluster.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when: update_nodepools != ""
