---

- name: Set list of nodepools to be updated
  set_fact:
    nodepools_to_update: "{{ update_nodepools.split(',') }}"

- include: update-cluster.yaml
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  vars:
    aws_region: "{{ a_cluster.providerConfig.region }}"
    kubectl: "{{ kubectl_commands[a_cluster.name] }}"
    kubeconfig: "{{ config_base }}/{{ a_cluster.name }}/admin.kubeconfig"
  when: update_nodepools != ""
