---
- name: Collect nodes
  command: >
    {{ kubectl }} --kubeconfig={{ kubeconfig }} get nodes
      -l nodepool={{ nodepool.name }}
      -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}'
  register: node_names

- name: Drain and Delete Nodes
  include: delete-node.yaml
  with_together:
    - "{{ instance_info.instances|map(attribute='private_dns_name')|list }}"
    - "{{ instance_info.instances|map(attribute='id')|list }}"
  loop_control:
    loop_var: aws_nodes
  vars:
    expected_node_count: "{{ nodepool.count }}"
    aws_node_name: "{{ aws_nodes.0 }}"
    aws_node_id: "{{ aws_nodes.1 }}"
  when:
    - aws_node_name in node_names.stdout_lines
    - nodepool.etcdConfigs is not defined
