---
- name: AWS ssh config generation
  include_role:
    name: '{{ playbook_dir }}/roles/kraken.ssh/kraken.ssh.aws'
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when: a_cluster.providerConfig.provider == 'aws'

- name: GKE ssh config generation
  include_role:
    name: '{{ playbook_dir }}/roles/kraken.ssh/kraken.ssh.gke'
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
  when: a_cluster.providerConfig.provider == 'gke' and not ( dryrun | bool )