---
- name: clean the generated folder
  file:
    path: "{{ config_base | expanduser }}/{{ a_cluster.name }}"
    state: absent
  with_items:
    - "{{ kraken_config.clusters }}"
  loop_control:
    loop_var: a_cluster
