---
- name: Generate etcd unit files from templates
  include: template-etcd.yaml
  with_subelements:
    - "{{ kraken_config.clusters }}"
    - nodePools
  loop_control:
    loop_var: cluster_node_tuple
  when: cluster_node_tuple.1.etcdConfig is defined
        and cluster_node_tuple.0.providerConfig.type == 'cloudinit'
