- name: Create a list of file for nodes
  find: >
    paths="{{ config_base | expanduser }}/{{ kraken_config.cluster }}"
    patterns="node.{{ item.name }}.*.part"
  register: node_list
  with_items: "{{ kraken_config.node }}"

- name: Generate node cloud init
  template: src=node.yaml.jinja2
    dest="{{ config_base | expanduser }}/{{ kraken_config.cluster }}/cloud-config/node.{{ item.0.name }}.cloud-config.yaml"
  with_together:
    - "{{ kraken_config.node }}"
    - "{{ node_list.results }}"