---
- name: Ensuring fabric directory exists
  shell: >
    mkdir -p {{ config_base | expanduser }}/{{ cluster.name }}/fabric
  ignore_errors: yes

- name: Generate canal deployment file
  template: src=canal.yaml.part.jinja2
            dest="{{ config_base | expanduser }}/{{ cluster.name }}/fabric/canal.yaml"

- name: Generate canal configuration file
  template: src=config.yaml.part.jinja2
            dest="{{ config_base | expanduser }}/{{ cluster.name }}/fabric/config.yaml"

- name: Wait for api server to become available in case it's not
  wait_for:
    host: "{{ item | regex_replace('https://','') }}"
    port: 443
    timeout: 600
  with_items: "{{ api_servers }}"

- name: check kube-networking namespace state
  command: >
    kubectl --kubeconfig={{ kubeconfig | expanduser }} get namespace kube-networking
  ignore_errors: yes
  changed_when: false
  register: kube_networking_namespace

- name: Ensure the kube-networking namespace exists
  command: >
    kubectl --kubeconfig={{ kubeconfig | expanduser }} create namespace kube-networking
  register: result
  retries: 120
  until: result|succeeded
  delay: 1
  when: not kube_networking_namespace.rc == 0
  ignore_errors: yes

- name: check kube-networking namespace state
  command: >
    kubectl --kubeconfig={{ kubeconfig | expanduser }} get namespace kube-networking
  ignore_errors: yes
  changed_when: false
  register: kube_networking_namespace

- name: Confirm kube-networking namespace created
  fail:
    msg: "kube-networking namespace creation failed"
  when: not kube_networking_namespace.rc == 0

- name: Deploy canal configuration
  command: >
    kubectl --kubeconfig={{ kubeconfig | expanduser }} apply -f {{ config_base | expanduser }}/{{ cluster.name }}/fabric/config.yaml

- name: Deploy canal daemonset
  command: >
    kubectl --kubeconfig={{ kubeconfig | expanduser }} apply -f {{ config_base | expanduser }}/{{ cluster.name }}/fabric/canal.yaml
