---
- name: Set cluster fact
  set_fact:
    cluster: "{{ a_cluster }}"

- name: Execute appropriate kubectl per minor version
  set_fact:
    kubectl: "/opt/cnct/kubernetes/{{ kubernetes_minor_version }}/bin/kubectl"
  vars:
    kubernetes_minor_version: "{{ kubernetes_minor_versions[cluster.name] }}"

- name: Ensuring fabric directory exists
  file:
    path: "{{ config_base | expanduser }}/{{ cluster.name }}/fabric"
    state: directory

- name: Generate canal deployment file
  template: src=canal.yaml.part.jinja2
            dest="{{ config_base | expanduser }}/{{ cluster.name }}/fabric/canal.yaml"

- name: Generate canal configuration file
  template: src=config.yaml.part.jinja2
            dest="{{ config_base | expanduser }}/{{ cluster.name }}/fabric/config.yaml"

- name: Wait for api server
  wait_for:
    host: "{{ item | regex_replace('https://','') }}"
    port: 443
    timeout: 600
  with_items: "{{ api_servers }}"
  vars:
    kubefn: "{{ config_base | expanduser }}/{{ cluster.name }}/admin.kubeconfig"
    kubeconfig: "{{ kubefn | is_file | ternary( kubefn, '/dev/null' ) }}"
    api_servers: "{{ lookup('file', kubeconfig) | from_yaml | json_query('clusters[*].cluster.server') }}"
  when: "{{ not (dryrun | bool) }}"

- name: check kube-networking namespace state
  command: >
    {{ kubectl }} --kubeconfig={{ kubeconfig | expanduser }} get namespace kube-networking
  ignore_errors: yes
  changed_when: false
  register: kube_networking_namespace
  when: "{{ not (dryrun | bool) }}"

- name: Ensure the kube-networking namespace exists
  command: >
    {{ kubectl }} --kubeconfig={{ kubeconfig | expanduser }} create namespace kube-networking
  register: result
  retries: 120
  until: result|succeeded
  delay: 1
  when: "{{ (not (dryrun | bool)) and (kube_networking_namespace | failed) }}"
  ignore_errors: yes

- name: check kube-networking namespace state
  command: >
    {{ kubectl }} --kubeconfig={{ kubeconfig | expanduser }} get namespace kube-networking
  ignore_errors: yes
  changed_when: false
  register: kube_networking_namespace
  when: "{{ not (dryrun | bool) }}"

- name: Confirm kube-networking namespace created
  fail:
    msg: "kube-networking namespace creation failed"
  when: "{{ (not (dryrun | bool)) and (kube_networking_namespace | failed) }}"

- name: Deploy canal configuration
  command: >
    {{ kubectl }} --kubeconfig={{ kubeconfig | expanduser }} apply -f {{ config_base | expanduser }}/{{ cluster.name }}/fabric/config.yaml --namespace=kube-networking
  when: "{{ not (dryrun | bool) }}"

- name: Deploy canal daemonset
  command: >
    {{ kubectl }} --kubeconfig={{ kubeconfig | expanduser }} apply -f {{ config_base | expanduser }}/{{ cluster.name }}/fabric/canal.yaml --namespace=kube-networking
  when: "{{ not (dryrun | bool) }}"
